#!/bin/sh
set -e

HOOKS_DIR=".git/hooks"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

cp .githooks/pre-commit "$HOOKS_DIR/pre-commit"
chmod +x "$HOOKS_DIR/pre-commit"
echo "Pre-commit hook installed."
